### ISSUE TITLE
Find and change tag to proper query in urls

### ISSUE THREAD

**Issue by DAreRodz** [worona/wp-org-connection-app-extension-worona#11]

**Comment by luisherranz** [comment]
It's impossible to load a tag list from its id, like:
http://demo.worona.org/?tag=15
http://demo.worona.org/?tag_id=15
http://demo.worona.org/?post_tag=15

The only thing which seems to work is using the slug:
http://demo.worona.dev/?tag=japan

Therefore, we need to change all the tag urls from their ids to their slugs.

**Comment by luisherranz** [comment]
The only moment which this may affect is when we don't have enough information and we don't have the tag link, but if we don't have the tag link, we don't have the tag slug either.

Won't fix for the moment, but in future router/connection versions.
