### ISSUE TITLE
Make date urls work

### ISSUE THREAD

**Issue by Poliuk** [worona/wp-org-connection-app-extension-worona#13]
> **Hacer las URLs de archivos por fecha funcionales en la versión Worona**

> Puede afectar a indexación. Aunque en adslzone.tv actualmente están desindexadas, sí llevan el atributo "follow" para seguir los enlaces. En otras webs es posible que estén indexadas. En cualquier caso, Google tiene esas URLs en su "lista" y las va a rastrear

**Comment by orballo** [comment]
Blocked until `wp-org-connection-app-extension-worona`  is refactored.
> https://github.com/worona/wp-org-connection-app-extension-worona/issues/16

**Comment by Poliuk** [comment]
**Moved to https://github.com/wp-pwa/wp-pwa-plugin/issues/17**
