### ISSUE TITLE
Error when filtering posts by tag

### ISSUE THREAD

**Issue by orballo** [worona/wp-org-connection-app-extension-worona#6]
`uncaught at newListRequestedSaga TypeError: Cannot read property 'pages' of undefined`

[Link to line where error ocurred](https://github.com/worona/wp-org-connection-app-extension-worona/blob/70ecc2feaa0291854806b0c76c7ffd0e1a4254b2/src/app/selectorCreators/index.js#L49)

**Comment by luisherranz** [comment]
Thanks @orballo, I'll take a look!
