### ISSUE TITLE
Change page titles dynamically (using <Head> component)

### ISSUE THREAD

**Issue by luisherranz** [worona/wp-org-connection-app-extension-worona#9]
I'm not sure the best place to do so, probably in connection.

**Comment by Poliuk** [comment]
```javascript
import Head from '@worona/next/head'

export default () =>
  <div>
    <Head>
      <title>My page title</title>
    </Head>
  </div>
```
> https://github.com/zeit/next.js/#populating-head

**Comment by orballo** [comment]
Implemented, but I installed `he` in `connection`. Maybe this package should be moved somewhere else, as it is installed as well in `saturn`.

**Comment by luisherranz** [comment]
What's it about?

**Comment by Poliuk** [comment]
The Yoast meta tags are now exposed:

> https://aztv.grupoadslzone.com/?rest_route=/wp/v2/posts/181842
```
yoast_meta: {
     yoast_wpseo_title: "Cómo ver online el Atlético de Madrid - Real Madrid",
     yoast_wpseo_metadesc: "Cómo ver online el Atlético de Madrid - Real Madrid. Cadena y principales aplicaciones móviles para visionar el encuentro.",
     yoast_wpseo_canonical: "https://aztv.grupoadslzone.com/2017/05/10/ver-online-atletico-madrid-real-madrid/",
     yoast_wpseo_homepage_title: "TV Zone : Televisión, Cine y más",
     yoast_wpseo_homepage_metadesc: "Portal de televisión y cine del Grupo ADSLZone con noticias de actualidad, análisis de películas, series y plataformas de streaming"
}
```

- **yoast_wpseo_title**, **yoast_wpseo_metadesc** and **yoast_wpseo_canonical** refer to the current post, tag or category.

- **yoast_wpseo_homepage_title** and **yoast_wpseo_homepage_metadesc** refer to the title and the description for the homepage.

**Comment by orballo** [comment]
Waiting for https://github.com/worona/wp-api-yoast-meta/issues/1

**Comment by Poliuk** [comment]
I'm still working on https://github.com/worona/wp-api-yoast-meta/issues/1 but you can already use the endpoint in demo. 

```json
{
    homepage_title: "Demo Worona",
    homepage_metadesc: "Just another WordPress site"
}
```
> https://demo.worona.org/?rest_route=/worona/v1/site-info

**Comment by Poliuk** [comment]
@orballo it's now live at https://aztv.grupoadslzone.com/?rest_route=/worona/v1/site-info as well ;)

**Comment by orballo** [comment]
I need to create `actions`, `reducers` and `sagas`. Retrieve info from `wpapi`, save it in the `store`, and then consume it in `Theme`.
